== References for Attribute Experiments

DIGEST FACC 2.1 - https://www.dgiwg.org/DIGEST

DGIWG DIGEST Disposition (Sunset Mandate) - http://portal.dgiwg.org/files/7827

NSG DIGEST Disposition (Sunset Mandate) - https://gwg.nga.mil/documents/asfe/DGIWG_FACC.htm

CDB 1.x Feature Data Dictionary - https://external.ogc.org/twiki_public/pub/CDBswg/WebHome/CDB_FDD.xlsx

NCV 2.0 Vocabulary - https://nsgreg.nga.mil/voc/registers.jsp?register=NCV

NAS 7.0 Application Schema - https://nsgreg.nga.mil/doc/view?i=3029

NAS 8.0 Application Schema - https://nsgreg.nga.mil/doc/view?i=3031

NAS X-3 Application Schema - https://nsgreg.nga.mil/doc/view?i=5042

GGDM 3.0 Feature Catalog - https://ggdm.erdc.dren.mil/pages/contents/v3.0.html

DGIWG Defence Geospatial Information Model (DGIM) - https://www.dgiwg.org/dgiwg-standards/205

Aeronautical Information Exchange Model (AIXM) - https://www.aixm.aero/

IHO Electronic Navigation Chart (ENC) S-57 Transfer Standard for Digital Hydrographic Data https://iho.int/uploads/user/pubs/standards/s-57/31Main.pdf

IHO Electronic Navigation Chart (ENC) S-100 Universal Hydrographic Data Model - https://iho.int/en/s-100-universal-hydrographic-data-model

ISO 18025:2014 Environment Data Coding Standard (EDCS) - https://standards.sedris.org/18025/

ISO 19109:20005 Geographic Information: Rules for Application Schema - https://www.iso.org/obp/ui/#iso:std:iso:19109:ed-2:v1:en

Web Ontology Language (OWL) - https://www.w3.org/OWL/

SE Core vs. GGDM Analysis - link:++SE Core to GGDM Gaps.xlsx++[Excel Worksheet]

TDS 6.0, TDS 7.0, GGDM 3.0, and CDB 1.0 Cross-walk - link:GGDM_to_CDB_Crosswalk_20200713.xlsx[Excel Worksheet]

Building Interior Standard Crosswalk - link:++Interior Assessment and Correlation.xlsx++[Excel Worksheet]

Geometric Progress IFC 4.3 Notes - link:++Assessment of IFC 4.docx++[Microsoft Word Document]
