== Subject
This Engineering Report documents a CDB 2.0 Conceptual Model as well as the results of CDB 2.0 rapid prototyping activites conducted during the 3D Geospatial Series Tech Sprint II - OGC CDB 2.0. This activity was performed in support of Special Operations Forces (SOF) Future Concepts. This effort hopes to accelerate evolution of the OGC CDB standard to meet the needs of planning, rehearsal, and Mission Command systems providing decision support to Special Operations Forces and enabling SOF tactical and operational advantage. OGC industry standards enable interoperability of geospatial data across systems and applications that SOF Operators and analysts use across warfighting functions.

== Executive Summary

(( The following is, as all texts in double square brackets, a helper text. Please remove this and all other helper texts once done. ))

(( The Executive Summary clause shall contain the key findings and results in a concise form. A more detailed description of the findings should be in the body of the report. ))

(( The Executive Summary shall contain a business value statement that should describe the value of this Engineering Report to improve interoperability, advance location-based technologies or realize innovations. ))

(( This section shall include precise descriptions of the requirements that have been addressed by the work documented in this Engineering Report; together with the research motivation that answers the fundamental question: What motivated us to address this topic in this report? ))

(( This section provides an overview of recommendations on how to further proceed with the achievements documented in this ER. ))

(( This section shall be between 1-3 pages.))

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
| Tracey Birch | CloudLake/USSOCOM SOF AT&L | Editor
| David Graham | Eaglecapsystems | Editor
| Carl Reed, PhD | Carl Reed & Associates | Editor
| Kevin Bentley | Cognitics | Contributor
| Holly Black | CAE | Contributor
| Hermann Bressard | Presagis | Contributor
| Patrick Cozzi | CESIUM | Contributor
| Brian Ford | FLightSAfety | Contributor
| Ryan Franz | FlightSafety | Contributor
| Jay Freeman | CAE | Contributor
| Jérôme Jacovella-St-Louis | Ecere | Contributor
| Greg Peele | Geometric Progress | Contributor
| Vaughn Whisker | ARL PSU | Contributor
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
