== Subject
This Engineering Report documents a CDB Experimental (CDB X) Conceptual Model as well as the results of CDB X rapid prototyping activites conducted during the 3D Geospatial Series Tech Sprint II - OGC CDB 2.0. This activity was performed in support of Special Operations Forces (SOF) Future Concepts. This effort hopes to accelerate evolution of the OGC CDB standard to meet the needs of planning, rehearsal, and Mission Command systems providing decision support to Special Operations Forces and enabling SOF tactical and operational advantage. OGC industry standards enable interoperability of geospatial data across systems and applications that SOF Operators and analysts use across warfighting functions.

CDB X - Meeting the requirements for tactical GEOINT that can be used across warfighting functions.

== Executive Summary

Since 2018 the CDB community has discussed and considered what CDB version 2.0 might might provide in terms of capabilities. These discussion also touched on architecture and related logical models. Many of these CDB 2.0 discussion have occured as part of the OGC standards work. More recently, other organizations such as SOCOM and NGA, have vigorously engaged in these discussions. However, progress has been relatively slow.

Therefore, in order to accelerate the development of CDB 2.0, in May 2020 SOFWERX announced the https://events.sofwerx.org/3dgeots/[3D Geospatial Series Tech Sprint II – OGC CDB 2.0]. In support of SOF Future Concepts, this effort hopes to accelerate evolution of the OGC CDB standard to meet the needs of planning, rehearsal, and Mission Command systems providing decision support to Special Operations Forces and enabling SOF tactical and operational advantage.

The CBD Tech Sprint was comprised of five (5) key work phases:

Phase 1: 22 June 2020 to 26 June 2020 Virtual Concept Development: In a series of virtual workshop conferences, participants discussed CDB 2.0 requirements and design objectives with a focus on defining conceptual and logical models for the CDB 2.0 standard. The discussion focused on five key topics: Attribution, 3D Models, Vector Data/GeoPackage, Coverage Tiling (and LoDs and general tiling), and Top Level Metadata. This models and related topics discussions served as the basis for technical experimentation in Phase 2.

Phase 2: 06 July 2020 to 31 July 2020 Virtual Tech Sprint: Participants, and/or their organizations, will provide prototype implementations of the conceptual model documented in Phase 1. Through technical integration experimentation, the model will be updated and refined.

Phase 3: 03 August 2020 to 28 August 2020 Engineering Report (ER): Participants will complete the project Engineering Report detailing the conceptual model and results of the technical integration experiments.

Phase 4: 07 September 2020 to 25 September 2020 Proposed Draft Specification: Participants will create a proposed draft specification for “CDB 2.0” based on work in the previous phases, to be submitted to the appropriate working groups within OGC, Khronos, and/or SISO.

Phase 5: 05 October 2020 to 30 October 2020 Final Report: Participants will write a final report summarizing activities to date, recommendations for the OGC SWG and other standards bodies to consider, and contributions of each participant.

=== Recommendations

The following are the recommendations for changes, enhancements, and design principals for not just CDB 2.0 but also CDB version 1.3. The version 1.3 chnages are viewed as important enhancement that resolve both existing user specified needs as well as helping to provide a transition path the version 2.0

==== Attribution

[updated Summary Attribution recommendations from updated 7-attributions.adoc code merge from Greg's branch into Master 201026_1500]

The subgroup recommends extending the current CDB XML metadata to add the NAS metamodel capabilities that are currently not supported. The CDB core conceptual model should not mandate any particular data dictionary or content, but rather provide the conceptual and logical metamodel for describing any ISO 19109 compliant application schema to the maximum extent practical. There should be no technical reason why one could not develop an extension profile for CDB for any particular data dictionary that complies with ISO 19109.

* Adopt NAS-compliant logical entity-attribute model for CDB X with extensions for CDB use cases
** Store all aspsects of feature and attribute dictionary in single SQLite file for portability and runtime performance
** Use GGDM 3.0 as the initial starting point for definitions to populate CDB X data dictionary
** Match up remaining CDB non-GGDM feature types and subcodes with latest NAS definitions where possible, matching subcodes to attributes where relevant and adding missing enumerant values where necessary (with associated NCV vocabulary)
** Augment NAS definitions with other open standards and new development
*** Match up missing maritime definitions to DGIM followed by IHO S-100 where possible, define NCV vocabulary for such integrated definitions
*** Match up missing aeronautics definitions to DGIM followed by AIXM where possible, define NCV vocabulary for such integrated definitions
*** Coordinate with OGC, NGA, and STE OWT to develop replacement building interior data model incorporating IFC/BIM, CityGML, IMDF, and other open standards
*** Coordinate with OGC, NGA, STE OWT, and civilian environment agencies to develop detailed data model for vegetation
*** Create data model and vocabulary for material and light point definitions and capture into existing material and lightpoint libraries
*** Define NCV vocabulary and NAS-compatible entity and attribute types for CDB feature types and subcodes totally missing in all other standards
** Remove CDB feature subcodes entirely; migrate to existing and new feature and attribute types instead in NAS-compliant structure
** Define entity types for CDB datasets and define "aggregation" relationships from feature types to containing datasets
** Capture feature-level, dataset-level, and database metadata as NAS-compliant attribution meeting the NSG Metadata Foundation (NMF) and ISO 19115
** Define functional role domains and create mechanism to organize attribution by domain for tailoring to runtime devices
* Delegate entity and attribute physical encoding choices to vector and 3D model containers instead of specifying globally
** Deprecate extended attributes entirely, to be removed in CDB X
** Delegate containerization of entity types (one per table, multiple in same table specified by F_CODE attribute, etc.) to vector and model containers
** Delegate decision whether to use class or instance attributes to individual vector and model containers rather than global data dictionary
** Delegate decision of whether to use FACC-like codes, NAS labels, or natural language names for entity types, attributes, and values to vector and model containers
** Delegate decision of whether to flatten complex feature relationships and attributes used GGDM attribute prefixing to vector and model containers
** Delegate decision of whether to flatten multi-valued and range-valued attributes using GGDM attribute prefixing to vector and model containers
** Specify minimum and maximum cardinality of multi-valued attributes in feature and attribute dictionary, allow containers to use a lower maximum if using GGDM attribute prefixing encoding
* Define backward-compatible extensions in CDB 1.3 to add constructs necessary to move toward NAS-compliant attribution
** Capture proposed NAS-complaint replacement feature dictionary in existing CDB metadata XML with necessary extensions
** Only use feature subcode 000 in replacement dictionary and deprecate use of feature subcodes to be removed in CDB X
** Add mechanism to mark numeric attributes as interval ranges (existing non-upgraded clients should see still attribute as single-valued and read mean value from associated unsuffixed attribute, use suffixed attributes for deviation and closure for upgraded clients to read)
** Add minumum and maximum cardinality elements for attribute definitions to specify mininum and maximum element count for multi-valued attributes (existing non-upgraded clients should just see attribute as scalar base value and will only read the first value from associated content, will see ordinal-suffixed attributes as separate attributes)
** Add list of valid attributes to datasets in CDB 1.x metadata XML files to match existing human-readable specification
** Add list of valid enumerants for each attribute in CDB 1.x CDB_Attributes.xml file to match existing human-readable specification
** Add list of valid attributes for each entity type as extension to CDB 1.x Feature_Data_Dictionary.xml to implement NAS-compliant per-entity attributes
** Update CDB 1.x CDB_Attributes.xml to allow specifying text pattern constraints through <Pattern> element and text codelists for text attributes via <Codelist> element
** Update CDB 1.x Feature_Data_Dictionary.xml for each feature to specify its generalization (base) entity type via <Generalization> element
** Update CDB 1.x Feature_Data_Dictionary.xml to add <Aggregation> element to define additional associated category for an entity type, or parent category for a category
** Existing category and subcategory XML structure will add implicit definitions and aggeregation links for the category/subcategory items as used by CDB 1.0 for model storage

`Recommendation 1 Extended Attributes - Version 1.3` The subgroup discussion on this topic is titled: https://github.com/sofwerx/cdb2-concept/issues/25[Should Extended Attributes be preserved at the logical data model level?] The suggestion is that the CDB SWG discuss this issue and possible solution as a possible change for CDB version 1.3. Some additional testing may be required to determine if this capability can be added to version 1.3 or not.

`Recommendation 2 Attribute default values - Version 1.3` The subgroup discussion on this topic is titled: https://github.com/sofwerx/cdb2-concept/issues/32[Attribute Default Values #32]. The recommendation is that Defaults.xml can be used to define global attribute defaults as well as per-dataset defaults. Doing per-entity defaults would be a straight forward extension that could be proposed for CDB 1.3 as a transition path. The subgroup suggests that the CDB SWG discussion this for possible inclusion in version 1.3. A change request for this approach to specifying default values is also suggested.

`Recommendation 3 Attribute Terms - Version 1.3` The subgroup discussion on this topic is titled: https://github.com/sofwerx/cdb2-concept/issues/31[Capture Attribute Terms (Enumerants) in Metadata #31]. Attributes describing qualitative values are present in CDB 1.2 and the list of valid values  for each attribute are documented in the human-readable specification with both the vocabulary term name and its integer numeric value (index). However, the machine-readable XML metadata does not contain any of this information and treats these attribute types as raw integers with only a minimum and maximum value constraint. It may make sense as a transition path to update CDB 1.3 to define additional XML elements in a backward compatible way to capture these definitions from the existing specification into the machine-readable XML metadata. The conceptual model in the CDB 1.2 specification does align with how GGDM treats such attributes, so there is no fundamental incompatibility, and the proposed CDB X dictionary design accounts for properly tracking the terms for qualitative attributes in a machine-readable way in SQLite.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization | Role
| David Graham | Eaglecapsystems | Editor
| Carl Reed, PhD | Carl Reed & Associates | Editor
| Kevin Bentley | Cognitics | Contributor
| Holly Black | CAE | Contributor
| Hermann Bressard | Presagis | Contributor
| Patrick Cozzi | CESIUM | Contributor
| Brian Ford | FlightSafety | Contributor
| Ryan Franz | FlightSafety | Contributor
| Jay Freeman | CAE | Contributor
| Jérôme Jacovella-St-Louis | Ecere | Contributor
| Michala Hill | Cognitics | Facilitator/Contributor
| Greg Peele | Geometric Progress | Contributor
| Vaughn Whisker | ARL PSU | Contributor
| Tracey Birch | CloudLake/USSOCOM SOF AT&L | Emeritus
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
