== Terms and definitions



For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

.NOTE: Delete the first three terms because they are examples.

&#9679; CDB Data Store ::

 A data store is a repository for persistently storing and managing collections of data which include not just repositories like databases, but also simpler store types such as simple files, metadata, models, etc. (https://www.information-management.com/glossary/d.html) 2020
 
 &#9679; coordinate reference system ::

 coordinate system that is related to the real world by a datum term name (source: ISO 19111)
 
&#9679; elevation ::

Synonym for “height”

&#9679; coverage ::

 feature that acts as a function to return values from its range for any direct position within its spatio-temporal domain, as defined in https://portal.opengeospatial.org/files/?artifact_id=19820[OGC Abstract Topic 6: Schema for coverage geometry and functions]

&#9679; height ::

Distance of a point from a chosen reference surface measured upward along a line perpendicular to that surface. [ISO 19111] Note 1 to entry: A height below the reference surface will have a negative value, which would embrace both gravity-related heights and ellipsoidal heights.

&#9679; repository ::

 a place that holds CDB data, makes CDB data available to use, and organizes CDB data in a logical manner. (Network of the National Library of Medicine) 2020
 
&#9679; tile ::
 
geometric  shape  with  known  properties  that  may  or  may  not  be  the  result  of  a  tiling  (tessellation)process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: “tile” is NOT a packaged blob of data to download in a chunky streaming optimization scheme! 

&#9679; tiling ::

in mathematics, a tiling (tessellation) is a collection of subsets of the space being tiled, i.e. tiles thatcover the space without gaps or overlaps.

===	Abbreviated terms

|===
|*COTS*	|Commercial Off The Shelf
|*CRS*	 |Coordinate Reference System
|*GGDM*	|Ground-Warfighter Geospatial Data Model
|*glTF*	|GL Transmission Format
|*LoD*  |Level of Detail
|*OTW*  |Out the Window
|*OWT*  |One world Terrain
|*SOF*  |Special Opertions Forces
|*STAC* |SpatioTemporal Asset Catalog
|===

