== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

*4.x* +
*authoritative data source* +
An information technology (IT) term used by system designers to identify a system process that assures the veracity of data sources.  These IT processes should be followed by all geospatial data providers.  The data may be original or it may come from one or more external sources all of which are validated for quality and accuracy.

(SOURCE: Authority and Authoritative Sources: Clarification of Terms and Concepts for Cadastral Data. FGDC/NIST 2008)

*4.x* +
*conceptual model* +
description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain. A conceptual model is explicitly chosen to be independent of design or implementation concerns.

(SOURCE: CEN ENV 1613:1995)

*4.x* +
*coverage* +
feature that acts as a function to return values from its range for any direct position within its spatio-temporal domain
 
*4.x* +
*coordinate reference system* +
coordinate system that is related to the real world by a datum 

(SOURCE: ISO 19111:2019 Geographic information — Referencing by coordinates)

*4.x* +
*dataset* +
A dataset is a collection of data, published or curated by a single agent. Data comes in many forms including numbers, words, pixels, imagery, sound and other multi-media, and potentially other types, any of which might be collected into a dataset. 

Note: There is an important distinction between a dataset as an abstract idea and a distribution as a manifestation of the dataset

(SOURCE: https://www.w3.org/TR/vocab-dcat-2/[W3C Data Catalog Vocabulary (DCAT) - Version 2], 2020)

*4.x* +
*Data Store* +

A data store is a repository for persistently storing and managing collections of data which include not just repositories like databases, but also simpler store types such as simple files, metadata, models, etc. 
 
(SOURCE: https://www.information-management.com/glossary/d.html:2020)
 
*4.x* +
*elevation* +
Synonym for “height”
 
(SOURCE: https://portal.opengeospatial.org/files/?artifact_id=19820[OGC Abstract Topic 6: Schema for coverage geometry and functions])

*4.x* +
*height* +
Distance of a point from a chosen reference surface measured upward along a line perpendicular to that surface. 
Note 1 to entry: A height below the reference surface will have a negative value, which would embrace both gravity-related heights and ellipsoidal heights.

(SOURCE: ISO 19111:2019 Geographic information — Referencing by Coordinates)

*4.x* +
*Metadata* +
information that captures the characteristics of a resource to represent the ‘who’, ‘what’, ‘when’, ‘where’,
‘why’, and ‘how’ of that resource.

(SOURCE: https://nsgreg.nga.mil/doc/view?i=4252&month=10&day=22&year=2019[National System for Geospatial Intelligence (NSG) Metadata Foundation (NMF) Version 3.0])

*4.x* +
*repository* +

a place that holds CDB data, makes CDB data available to use, and organizes CDB data in a logical manner. (Network of the National Library of Medicine) 2020
 
*4.x* +
*resource* +
identifiable asset or means that fulfils a requirement

NOTE: A web resource, or simply resource, is any identifiable thing, whether digital, physical, or abstract.

(SOURCE: ISO:19115-1:2014 Geographic information — Metadata — Part 1: Fundamentals)

&#9679; tile ::
 
geometric  shape  with  known  properties  that  may  or  may  not  be  the  result  of  a  tiling  (tessellation)process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: “tile” is NOT a packaged blob of data to download in a chunky streaming optimization scheme! 

&#9679; tiling ::

in mathematics, a tiling (tessellation) is a collection of subsets of the space being tiled, i.e. tiles thatcover the space without gaps or overlaps.

===	Abbreviated terms

|===
|*COTS*	|Commercial Off The Shelf
|*CRS*	 |Coordinate Reference System
|*GGDM*	|Ground-Warfighter Geospatial Data Model
|*GPKG* |GeoPackage
|*glTF*	|GL Transmission Format
|*LoD*  |Level of Detail
|*MC*   |Mission Command
|*OTW*  |Out the Window
|*OWT*  |One World Terrain
|*PBR*  |Physically-Based Rendering (PBR)
|*SOF*  |Special Operations Forces
|*STAC* |SpatioTemporal Asset Catalog
|===

