[[Overview]]
== Overview

<<BackgroundClause,Section 5>> CDB 2.0 - Background and History: Provides the background and history of CDB to provide the context for the CDB-X work described in this Engineering Report.

<<CDB2Models,Section 6>> CDB X Design Goals, Use Cases, and Conceptual/Logical Models: Documents any models, such as the OGC/ISO Simple Features geometry model, that are germane to the CDB-X work.

<<Attribution,Section 7>> Attribution in CDB-X: Section 7 discusses the Attribution Topic and the work and recommendations of the Attribution Subgroup.

<<vectorgpkg,Section 8>> CDB Vector Data in Large GeoPackage Containers: Documents experiments to determine the viability of storing very large volumes of vector data in a smaller number of large GeoPackage files rather than a very large number of small Shapefiles.

<<threedcontent,Section 9>> 3D Models and Other 3D Content: Discusses the proposal to use glTF to encode and store 3D models in the CDB-XX data store

<<metadata,Section 10>> CDB X Metadata and Integration: This section discusses metadata in CDB-X.

<<tiling,Section 11>> Tiling and packaging of data layers: This section evaluates and discusses approaches to packaging one or more data layers in GeoPackages (including coverage, vector and 3D data) for CDB-X.
