[[vectorgpkg]]

== Vector/Coverage Data and GeoPackage

This clause provides discussion of 2.0 Vector Data and GeoPackage requirements and the results of the prototyping activities.


=== General

Any tiling schemes specified in a CDB X data store (repository) SHALL be based on and consistent with the:

* https://portal.ogc.org/files/?artifact_id=92962&version=1[OGC Core Tiling Conceptual and Logical Models for 2D Euclidean Space] (19-014r3)
* https://www.ogc.org/standards/tms[OGC Two Dimensional Tile Matrix Set Standard] (17-083r2)

==== OGC Core Tiling Conceptual and Logical Models for 2D Euclidean Space

This OGC Abstract Specification consists of two Parts: A General Tiling Conceptual Model and, basedon the Conceptual Model, a Logical Model for the Tessellation (Tiling) of 2D Euclidean Space.Tiling  of  2D  Euclidean  space  is  the  most  commonly  known  approach  to  partitioning  space  intraditional  geospatial  technology.  However,  there  are  also  common  elements  and/or  semantics  forany approach to partitioning space in any dimension. The logical model in this document defines aset  common  required  elements  and  then  follows  with  more  specific  requirements  for  the  twodimensional case.

Part  1  of  the  Abstract  Specification  describes  a  general  tiling  conceptual  model.  The  conceptualmodel  is  applicable  to  any  dimension.  The  conceptual  model  makes  no  assumptions  regardingcontent,  use  cases,  implementation  scenarios,  or  how  the  space  is  to  be  tessellated  (tiled).  Theconceptual model is abstract and cannot be implemented as is.

Part  2  of  this  Abstract  Specification  defines  a  detailed  logical  model  for  the  tessellation  of  2DEuclidean  Space.  One  or  more  logical  models  are  required  to  provide  the  requirements  andstructure  necessary  for  implementation.  Therefore,  in  addition  to  the  conceptual  model,  thisAbstract Specification also specifies a core logical model for the 2D planar (Euclidean) use case.

==== OGC Two Dimensional Tile Matrix Set Standard

The OGC Tile Matrix Set standard defines the rules and requirements for a tile matrix set as a way to index space based on a set of regular grids defining a domain (tile matrix) for a limited list of scales in a Coordinate Reference System (CRS) as defined in [OGC 08-015r2] Abstract Specification Topic 2: Spatial Referencing by Coordinates. Each tile matrix is divided into regular tiles. In a tile matrix set, a tile can be univocally identified by a tile column a tile row and a tile matrix identifier. This document presents a data structure defining the properties of the tile matrix set in both UML diagrams and in tabular form. This document also presents a data structure to define a subset of a tile matrix set called tile matrix set limits. XML and JSON encodings are suggested both for tile matrix sets and tile matrix set limits. Finally, the document offers practical examples of tile matrix sets both for common global projections and for specific regions.

=== Design Objectives for CDB X Tiling and LoDs and Layers

The following are the key design principals for a CDB X tiling, levels of detail, and layering.

* OGC GeoPackage structured containers are a primary storage format for derived vector data layers, coverages, and other data types as identified (`TBD`). The two OGC Standards of relevance are https://portal.opengeospatial.org/files/12-128r15[OGC GeoPackage version 1.1] and http://docs.opengeospatial.org/is/17-066r1/17-066r1.html[OGC GeoPackage Extension for Tiled Gridded Coverage Data].
* Have metadata for whole dataset listing how data layers are regrouped in GeoPackages (LOD grouping and data layer grouping)
* Store imagery in GeoPackage according to the tiling scheme specified below (`need anchor`)
* Store coverage data in GeoPackage according to the tiling scheme specified below (`need anchor`). Suggested coverage types based on current CDB standard and user specified requirements: (Spherical body surface): Elevation models, imagery, multi-spectral, raster (such as classified satellite imagery). Should be extensible to support other types.
* Coordinate Reference System is WGS 84 with epoch encoding (same as current CDB Standard except for epoch).
* Must enable a "relatively" easy migration path from the CDB 1.1/1.2 tiling/LoD structure into the CDB X structure.

=== Proposed CDB X Tiling Structure


